/* VID-GEN landing: deep dark canvas, vivid four-color brand accents, human creator-first messaging, and motion-safe reveals. */
import { ArrowRight, Check, Facebook, Instagram, Play, Sparkles, Twitter, Youtube, Zap } from "lucide-react";
import { Link } from "wouter";

const features = [
  ["01", "Video Scripts", "Turn a rough thought into a clear script with a beginning, middle, and reason to keep watching.", "red"],
  ["02", "Captions", "Write captions that sound like you, ready for every channel and every moment.", "blue"],
  ["03", "Hashtags", "Find the language your audience already uses without losing your point of view.", "green"],
  ["04", "Auto-Post", "Move from finished idea to scheduled publishing without opening five tabs.", "yellow"],
] as const;
const platforms = [[Youtube, "YouTube"], [Instagram, "Instagram"], [Twitter, "Twitter / X"], [Facebook, "Facebook"]] as const;

export default function Home() {
  return <div className="marketing-page">
    <div className="ambient-orb orb-red" /><div className="ambient-orb orb-blue" /><div className="ambient-grid" />
    <header className="marketing-nav"><Link href="/" className="marketing-brand"><span className="brand-mark"><Sparkles size={15} /></span><span>VID<span className="brand-red">·</span>GEN</span></Link><nav><a href="#features">Features</a><a href="#platforms">Platforms</a><a href="#pricing">Pricing</a></nav><div className="nav-ctas"><Link href="/login" className="nav-login">Log in</Link><Link href="/signup" className="button button-green button-small">Get started <ArrowRight size={15} /></Link></div></header>
    <main>
      <section className="marketing-hero"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line" /> YOUR NEXT POST STARTS HERE</div><h1>Create.<br /><span className="hero-word red-text">Generate.</span><br /><span className="hero-word blue-text">Dominate.</span></h1><p>AI-powered content for every platform — posted automatically. Give VID-GEN the direction. Keep your voice.</p><div className="hero-actions"><Link href="/signup" className="button button-green">Get started free <ArrowRight size={17} /></Link><a href="#demo" className="button button-outline"><span className="play-icon"><Play size={12} fill="currentColor" /></span> Watch demo</a></div><div className="hero-proof"><span className="proof-stack"><i /><i /><i /></span><span>Made for creators who have something to say.</span></div></div><div className="hero-visual" id="demo"><div className="hero-window"><div className="window-bar"><span><i /><i /><i /></span><small>vid-gen / new brief</small><span className="window-status"><b /> LIVE</span></div><div className="prompt-card"><span className="mini-label">PROMPT / 001</span><p>"A short video about building a slower, more intentional morning routine."</p><div className="prompt-footer"><span className="tag-pill"><Zap size={12} /> Full package</span><span>Generating...</span></div></div><div className="output-list"><div className="output-row"><span className="output-icon red-bg">S</span><span><b>Video script</b><small>45 sec · ready to edit</small></span><Check size={16} className="green-icon" /></div><div className="output-row"><span className="output-icon blue-bg">C</span><span><b>Caption set</b><small>3 versions · ready to post</small></span><Check size={16} className="green-icon" /></div><div className="output-row"><span className="output-icon yellow-bg">#</span><span><b>Hashtag pack</b><small>12 tags · researched</small></span><Check size={16} className="green-icon" /></div></div><div className="publish-strip"><span><span className="pulse-dot" /> Publishing queue</span><strong>12 posts ready <ArrowRight size={14} /></strong></div></div><div className="hero-float float-one"><span className="float-icon green-bg"><Check size={13} /></span><span><b>Posted</b><small>2 min ago</small></span></div><div className="hero-float float-two"><span className="float-icon yellow-bg"><Sparkles size={13} /></span><span><b>4 outputs</b><small>from one prompt</small></span></div></div></section>
      <section className="platform-strip" id="platforms"><span className="mini-label">READY FOR THE PLACES YOU ALREADY SHOW UP</span><div>{platforms.map(([Icon, name]) => <span key={name}><Icon size={17} />{name}</span>)}</div></section>
      <section className="section-block" id="features"><div className="section-intro"><div className="eyebrow"><span className="eyebrow-line" /> THE WHOLE LOOP</div><h2>One idea in.<br /><em>Everything out.</em></h2><p>One workspace for the work behind showing up consistently. Write less from scratch. Keep more of what makes your voice yours.</p></div><div className="feature-grid">{features.map(([num, title, text, color]) => <article className={`feature-card ${color}`} key={title}><span className="feature-number">{num}</span><div className="feature-icon"><Sparkles size={18} /></div><h3>{title}</h3><p>{text}</p><ArrowRight size={18} className="feature-arrow" /></article>)}</div></section>
      <section className="pricing-section" id="pricing"><div className="section-intro centered"><div className="eyebrow"><span className="eyebrow-line" /> SIMPLE PLANS</div><h2>Pick your pace.<br /><em>Keep your momentum.</em></h2></div><div className="pricing-grid"><Price name="Free" price="$0" text="For getting your first rhythm going." features={["10 generations / month", "2 connected platforms", "Basic scheduling"]} tone="blue" /><Price name="Pro" price="$19" text="For creators ready to publish consistently." features={["Unlimited generations", "All platform connections", "Advanced scheduling", "Voice & tone presets"]} tone="green" featured /><Price name="Creator" price="$49" text="For small teams building a bigger presence." features={["Everything in Pro", "3 team seats", "Analytics workspace", "Priority support"]} tone="red" /></div></section>
      <section className="final-cta"><div className="eyebrow"><span className="eyebrow-line" /> START WITH ONE GOOD IDEA</div><h2>Create once.<br /><em>Show up everywhere.</em></h2><Link href="/signup" className="button button-green">Build your first package <ArrowRight size={17} /></Link></section>
    </main>
    <footer className="marketing-footer"><Link href="/" className="marketing-brand"><span className="brand-mark"><Sparkles size={13} /></span><span>VID<span className="brand-red">·</span>GEN</span></Link><span>© 2026 VID-GEN</span><div><a href="#features">Features</a><a href="#pricing">Pricing</a><Link href="/login">Log in</Link></div></footer>
  </div>;
}

function Price({ name, price, text, features, tone, featured = false }: { name: string; price: string; text: string; features: string[]; tone: string; featured?: boolean }) {
  return <article className={`price-card ${tone} ${featured ? "featured" : ""}`}>{featured && <span className="popular-pill">MOST POPULAR</span>}<span className="price-name">{name}</span><div className="price-value">{price}<small>/month</small></div><p>{text}</p><ul>{features.map(item => <li key={item}><Check size={14} />{item}</li>)}</ul><Link href="/signup" className={`button ${tone === "green" ? "button-green" : "button-outline"}`}>Choose {name} <ArrowRight size={15} /></Link></article>;
}
